#!/usr/bin/with-contenv bash

if [ -z "${CUSTOM_RPC_TOKEN}" ]; then
  exit 1
fi
 
export RPC_TOKEN="${CUSTOM_RPC_TOKEN:-$(openssl rand -base64 32)}"

if [ -z "${CUSTOM_RPC_TOKEN}" ]; then
  exit 1
fi


export OVERRIDE_OPTIONS=("${CUSTOM_OVERRIDE_OPTIONS}")

touch /data/config/custom.conf

chown -R abc:abc \
         /data/aria2c-webui \
         /data/config \
         /data/downloads

chown -R abc:abc  \
        /var/lib/nginx

echo "RPC Token: ${RPC_TOKEN}"

