#!/usr/bin/with-contenv bash

if [ -z "${CUSTOM_RPC_TOKEN}" ]; then
  exit 1
fi

printf "${CUSTOM_RPC_TOKEN:-$(openssl rand -base64 32)}" > /var/run/s6/container_environment/RPC_TOKEN
printf "("${CUSTOM_OVERRIDE_OPTIONS}")" > /var/run/s6/container_environment/OVERRIDE_OPTIONS

touch /data/config/custom.conf

chown -R abc:abc \
         /data/aria2c-webui \
         /data/config \
         /data/downloads

chown -R abc:abc  \
        /var/lib/nginx

echo "RPC Token: ${RPC_TOKEN}"

